vegetable(artichoke).
vegetable(asparagus).
vegetable(broccoli).
vegetable(cabbage).
vegetable(carrots).
vegetable(cauliflower).
vegetable(coriander).
vegetable(cucumber).
vegetable(eggplant).
vegetable(green_beans).
vegetable(kale).
vegetable(okra).
vegetable(onions).
vegetable(peas).
vegetable(potato).
vegetable(shiitake).
vegetable(spinach).
vegetable(summer_squash).
vegetable(tomatoes).
vegetable(artichoke).
 
fruit(apple).
fruit(apricots).
fruit(banana).
fruit(blackberries).
fruit(cherries).
fruit(corn).
fruit(grape).
fruit(guava).
fruit(kiwi).
fruit(lemon).
fruit(lychee).
fruit(mango).
fruit(peach).
fruit(pineapple).
fruit(watermelon).
fruit(durian).
 
contain_vit(artichoke,a).
contain_vit(artichoke,b1).
contain_vit(artichoke,b2).
contain_vit(artichoke,b6).
contain_vit(artichoke,c).
contain_vit(asparagus,a).
contain_vit(asparagus,b1).
contain_vit(asparagus,b2).
contain_vit(asparagus,b6).
contain_vit(asparagus,c).
contain_vit(asparagus,e).
contain_vit(broccoli,a).
contain_vit(broccoli,c).
contain_vit(broccoli,k).
contain_vit(cabbage,a).
contain_vit(cabbage,b1).
contain_vit(cabbage,b2).
contain_vit(cabbage,b6).
contain_vit(cabbage,k).
contain_vit(carrots,a).
contain_vit(carrots,b1).
contain_vit(carrots,b2).
contain_vit(carrots,b6).
contain_vit(carrots,c).
contain_vit(cauliflower,c).
contain_vit(cauliflower,k).
contain_vit(cauliflower,b6).
contain_vit(coriander,c).
contain_vit(coriander,k).
contain_vit(cucumber,a).
contain_vit(cucumber,b1).
contain_vit(cucumber,b2).
contain_vit(cucumber,b6).
contain_vit(cucumber,c).
contain_vit(eggplant,c).
contain_vit(eggplant,k).
contain_vit(eggplant,b6).
contain_vit(green_beans,c).
contain_vit(green_beans,k).
contain_vit(kale,a).
contain_vit(kaler,c).
contain_vit(kaler,k).
contain_vit(kaler,b6).
contain_vit(okra,c).
contain_vit(okra,b).
contain_vit(okra,k).
contain_vit(onions,c).
contain_vit(peas,c).
contain_vit(peas,b).
contain_vit(peas,k).
contain_vit(peppers,a).
contain_vit(peppers,c).
contain_vit(peppers,k).
contain_vit(peppers,b6).
contain_vit(potato,c).
contain_vit(potato,b6).
contain_vit(shiitake,b1).
contain_vit(shiitake,d).
contain_vit(spinach,a).
contain_vit(spinach,c).
contain_vit(spinach,k).
contain_vit(summer_squash,c).
contain_vit(summer_squash,k).
contain_vit(tomatoes,c).
contain_vit(tomatoes,k).

contain_vit(apple,c).
contain_vit(apricots,a).
contain_vit(apricots,c).
contain_vit(banana,a).
contain_vit(banana,b1).
contain_vit(banana,b2).
contain_vit(banana,b6).
contain_vit(banana,c).
contain_vit(blackberries,b1).
contain_vit(blackberries,b6).
contain_vit(blackberries,c).
contain_vit(cherries,a).
contain_vit(cherries,b1).
contain_vit(cherries,b2).
contain_vit(cherries,b6).
contain_vit(corn,a).
contain_vit(corn,b).
contain_vit(corn,c).
contain_vit(grape,a).
contain_vit(grape,c).
contain_vit(grape,k).
contain_vit(guava,a).
contain_vit(guava,b).
contain_vit(guava,c).
contain_vit(kiwi,b6).
contain_vit(kiwi,c).
contain_vit(lemon,c).
contain_vit(lychee,b1).
contain_vit(lychee,c).
contain_vit(mango,a).
contain_vit(mango,b1).
contain_vit(mango,b2).
contain_vit(mango,b3).
contain_vit(peach,a).
contain_vit(peach,b2).
contain_vit(peach,c).
contain_vit(peach,k).
contain_vit(pineapple,b1).
contain_vit(pineapple,b2).
contain_vit(pineapple,b5).
contain_vit(pineapple,b6).
contain_vit(pineapple,c).
contain_vit(watermelon,a).
contain_vit(watermelon,b6).
contain_vit(watermelon,c).
contain_vit(durian,a).
contain_vit(durian,b9).
contain_vit(durian,c).

symptom_in_organ(dry_skin,skin).
symptom_in_organ(vision_deterioration,eye).
symptom_in_organ(bitots_spots,eye).
symptom_in_organ(fast_heart_rate,heart).
symptom_in_organ(shortness_of_breath,lung).
symptom_in_organ(numbness,body).
symptom_in_organ(confusion,brain).
symptom_in_organ(fatigue_and_tiredness,heart).
symptom_in_organ(change_in_mood,brain).
symptom_in_organ(soreness_of_throat,throat).
symptom_in_organ(skin_rashes,skin).
symptom_in_organ(cracked_lips,skin).
symptom_in_organ(depression,brain).
symptom_in_organ(easy_bruising,body).
symptom_in_organ(painful_swollen_joints,body).
symptom_in_organ(muscle_pain,body).
symptom_in_organ(bone_and_back_pain,body).
symptom_in_organ(immune_system_problems,body).
symptom_in_organ(blood_in_the_urine_or_stool,bladder).
symptom_in_organ(heavy_menstrual_periods,ovary).
symptom_in_organ(phlegm,throat).
symptom_in_organ(gray_hair,head).
symptom_in_organ(tongue_swelling,throat).

vit_cure_symptom(a,dry_skin).
vit_cure_symptom(a,vision_deterioration).
vit_cure_symptom(a,bitots_spots).
vit_cure_symptom(b1,fast_heart_rate).
vit_cure_symptom(b1,shortness_of_breath).
vit_cure_symptom(b1,numbness).
vit_cure_symptom(b1,confusion).
vit_cure_symptom(b2,fatigue_and_tiredness).
vit_cure_symptom(b2,change_in_mood).
vit_cure_symptom(b2,dry_skin).
vit_cure_symptom(b2,soreness_of_throat).
vit_cure_symptom(b6,fatigue_and_tiredness).
vit_cure_symptom(b6,skin_rashes).
vit_cure_symptom(b6,cracked_lips).
vit_cure_symptom(b9,fatigue_and_tiredness).
vit_cure_symptom(b9,gray_hair).
vit_cure_symptom(b9,tongue_swelling).
vit_cure_symptom(b12,fatigue_and_tiredness).
vit_cure_symptom(b12,shortness_of_breath).
vit_cure_symptom(b12,depression).
vit_cure_symptom(c,dry_skin).
vit_cure_symptom(c,easy_bruising).
vit_cure_symptom(c,painful).
vit_cure_symptom(c,swollen_joints).
vit_cure_symptom(c,have_phlegm).
vit_cure_symptom(d,muscle_pain).
vit_cure_symptom(d,fatigue_and_tiredness).
vit_cure_symptom(d,bone_pain).
vit_cure_symptom(d,back_pain).
vit_cure_symptom(e,muscle_pain).
vit_cure_symptom(e,immune_system_problems).
vit_cure_symptom(e,vision_deterioration).
vit_cure_symptom(k,blood_in_the_urine_or_stool).
vit_cure_symptom(k,easy_bruising).
vit_cure_symptom(k,heavy_menstrual_periods).
vit_cure_symptom(k,have_phlegm).